#include "Generator.hpp"

namespace obr {
namespace {

constexpr int kLink = 128;
constexpr int kObj = 129;
constexpr int kKey = 130;
constexpr int kVal = 131;
constexpr int kMode = 132;
constexpr int kSlot = 133;
constexpr int kFlag = 134;
constexpr int kCheapLink = 136;
constexpr int kCheapSize = 137;
constexpr int kCheapBase = 138;
constexpr int kFindLink = 140;
constexpr int kFindObj = 141;
constexpr int kFindKey = 142;
constexpr int kFindSlots = 143;
constexpr int kFindMask = 144;
constexpr int kFindStart = 145;
constexpr int kFindTomb = 146;
constexpr int kFindStride = 147;
constexpr int kFindIndex = 148;
constexpr int kFindMode = 149;
constexpr int kFindAddr = 139;
constexpr int kSeqLink = 150;
constexpr int kSeqA = 151;
constexpr int kSeqB = 152;
constexpr int kSeqLen = 153;
constexpr int kSeqI = 154;
constexpr int kGrowLink = 160;
constexpr int kGrowObj = 161;
constexpr int kGrowCap = 162;
constexpr int kGrowNew = 163;
constexpr int kGrowOld = 164;
constexpr int kGrowSlots = 165;
constexpr int kGrowStride = 166;
constexpr int kGrowMode = 167;
constexpr int kGrowI = 168;
constexpr int kGrowKey = 169;
constexpr int kGrowVal = 170;

std::string cell(int index) { return std::to_string(kUi + index * 64); }

}  // namespace

void Generator::markCollect() { needCollect_ = true; }

void Generator::restoreFrame() {
  emit("load.64 r4, " + std::to_string(kSp));
  emit("place r5, " + std::to_string(frameBits()));
  emit("sub r4, r4, r5");
  emit("store.64 r4, " + std::to_string(kFrame));
  frameHeld_ = true;
}

void Generator::emitCollectCall(const std::string& label) {
  markCollect();
  emit("call " + label);
  restoreFrame();
}

void Generator::emitCollectNew(const Expr& expr) {
  if (expr.type == TypeKind::Array) {
    gen(expr.kids[0]);
    emitCollectCall("obranew");
    return;
  }
  const char* label = "obrlnew";
  if (expr.type == TypeKind::Set) label = "obrsnew";
  if (expr.type == TypeKind::Map) label = "obrmnew";
  emitCollectCall(label);
}

void Generator::emitElementAddress(const Expr& box, const Expr& index) {
  gen(box);
  const int saved = words_ + temp_;
  hold();
  storeSlot(saved, TypeKind::Long);
  gen(index);
  copy(1, 0);
  loadSlot(saved, TypeKind::Long);
  release();
  emitCollectCall(box.type == TypeKind::Array ? "obrcidx" : "obrlidx");
}

namespace {

int collectMode(TypeKind key) {
  if (key == TypeKind::String) return 1;
  if (key == TypeKind::Float || key == TypeKind::Double) return 2;
  return 0;
}

}  // namespace

void Generator::emitCollectMethod(const Expr& expr) {
  const int code = static_cast<int>(expr.integer);
  const int mode = collectMode(expr.kids[0].pointee);
  const bool map = expr.kids[0].type == TypeKind::Map;
  const int stride = map ? 192 : 128;
  if (code == -20) {
    gen(expr.kids[1]);
    const int valueSlot = words_ + temp_;
    hold();
    storeSlot(valueSlot, TypeKind::Long);
    gen(expr.kids[0]);
    const int objSlot = words_ + temp_;
    hold();
    storeSlot(objSlot, TypeKind::Long);
    loadSlot(valueSlot, TypeKind::Long);
    copy(1, 0);
    loadSlot(objSlot, TypeKind::Long);
    release();
    release();
    emitCollectCall("obrlpush");
    return;
  }
  if (code == -21) {
    gen(expr.kids[0]);
    emitCollectCall("obrlpop");
    return;
  }
  if (code == -24) {
    gen(expr.kids[2]);
    const int valueSlot = words_ + temp_;
    hold();
    storeSlot(valueSlot, TypeKind::Long);
    gen(expr.kids[1]);
    const int keySlot = words_ + temp_;
    hold();
    storeSlot(keySlot, TypeKind::Long);
    gen(expr.kids[0]);
    const int objSlot = words_ + temp_;
    hold();
    storeSlot(objSlot, TypeKind::Long);
    loadSlot(keySlot, TypeKind::Long);
    copy(1, 0);
    loadSlot(valueSlot, TypeKind::Long);
    copy(2, 0);
    loadSlot(objSlot, TypeKind::Long);
    release();
    release();
    release();
    emit("place r3, " + std::to_string(mode));
    emitCollectCall("obrmput");
    return;
  }
  gen(expr.kids[1]);
  const int keySlot = words_ + temp_;
  hold();
  storeSlot(keySlot, TypeKind::Long);
  gen(expr.kids[0]);
  const int objSlot = words_ + temp_;
  hold();
  storeSlot(objSlot, TypeKind::Long);
  loadSlot(keySlot, TypeKind::Long);
  copy(1, 0);
  loadSlot(objSlot, TypeKind::Long);
  release();
  release();
  emit("place r3, " + std::to_string(mode));
  if (code == -22 || code == -25) emit("place r2, " + std::to_string(stride));
  if (code == -22) emitCollectCall("obrhas");
  else if (code == -25) emitCollectCall("obrremove");
  else if (code == -26) emitCollectCall("obrget");
  else emitCollectCall("obrsadd");
}

void Generator::emitCollectRoutines() {
  const auto at = [](int index) { return cell(index); };
  auto jump = [&](const std::string& label) {
    emit("place r6, 1");
    emit("jnz r6, " + label);
  };

  emit("obrhalt:");
  emit("halt");

  emit("obrcheap:");
  emit("store.64 r7, " + at(kCheapLink));
  emit("store.64 r0, " + at(kCheapSize));
  emit("load.64 r4, " + std::to_string(kHeapPtr));
  emit("place r5, 0");
  emit("eq r1, r4, r5");
  emit("jz r1, obrcheap_ready");
  emit("place r4, " + std::to_string(kHeap));
  emit("obrcheap_ready:");
  emit("store.64 r4, " + at(kCheapBase));
  emit("add r4, r4, r0");
  emit("store.64 r4, " + std::to_string(kHeapPtr));
  emit("load.64 r0, " + at(kCheapBase));
  emit("load.64 r2, " + at(kCheapSize));
  emit("place r1, 0");
  emit("obrcheap_loop:");
  emit("lt r3, r1, r2");
  emit("jz r3, obrcheap_done");
  emit("add r4, r0, r1");
  emit("place r5, 0");
  emit("sti.64 r5, r4");
  emit("place r5, 64");
  emit("add r1, r1, r5");
  jump("obrcheap_loop");
  emit("obrcheap_done:");
  emit("load.64 r7, " + at(kCheapLink));
  emit("ret");

  emit("obrmix:");
  emit("store.64 r7, " + at(kSeqLink));
  emit("or r1, r0, r0");
  emit("place r2, 16");
  emit("shr r1, r1, r2");
  emit("xor r0, r0, r1");
  emit("load.64 r7, " + at(kSeqLink));
  emit("ret");

  emit("obrhash:");
  emit("store.64 r7, " + at(kSeqLink));
  emit("place r1, 0");
  emit("eq r2, r0, r1");
  emit("jnz r2, obrhash_none");
  emit("ldi.64 r2, r0");
  emit("store.64 r0, " + at(kSeqA));
  emit("store.64 r2, " + at(kSeqLen));
  emit("place r3, 5381");
  emit("place r4, 0");
  emit("obrhash_loop:");
  emit("lt r5, r4, r2");
  emit("jz r5, obrhash_done");
  emit("place r5, 8");
  emit("mul r5, r4, r5");
  emit("place r1, 64");
  emit("add r5, r5, r1");
  emit("load.64 r0, " + at(kSeqA));
  emit("add r5, r0, r5");
  emit("ldi.octet r5, r5");
  emit("place r1, 33");
  emit("mul r3, r3, r1");
  emit("add r3, r3, r5");
  emit("place r1, 1");
  emit("add r4, r4, r1");
  emit("load.64 r2, " + at(kSeqLen));
  jump("obrhash_loop");
  emit("obrhash_done:");
  emit("or r0, r3, r3");
  emit("load.64 r7, " + at(kSeqLink));
  emit("ret");
  emit("obrhash_none:");
  emit("place r0, 0");
  emit("load.64 r7, " + at(kSeqLink));
  emit("ret");

  emit("obrseq:");
  emit("store.64 r7, " + at(kSeqLink));
  emit("eq r2, r0, r1");
  emit("jnz r2, obrseq_yes");
  emit("place r2, 0");
  emit("eq r3, r0, r2");
  emit("jnz r3, obrseq_no");
  emit("eq r3, r1, r2");
  emit("jnz r3, obrseq_no");
  emit("store.64 r0, " + at(kSeqA));
  emit("store.64 r1, " + at(kSeqB));
  emit("ldi.64 r2, r0");
  emit("ldi.64 r3, r1");
  emit("eq r4, r2, r3");
  emit("jz r4, obrseq_no");
  emit("store.64 r2, " + at(kSeqLen));
  emit("place r4, 0");
  emit("obrseq_loop:");
  emit("load.64 r2, " + at(kSeqLen));
  emit("lt r5, r4, r2");
  emit("jz r5, obrseq_yes");
  emit("store.64 r4, " + at(kSeqI));
  emit("place r5, 8");
  emit("mul r5, r4, r5");
  emit("place r1, 64");
  emit("add r5, r5, r1");
  emit("load.64 r0, " + at(kSeqA));
  emit("add r5, r0, r5");
  emit("ldi.octet r6, r5");
  emit("load.64 r4, " + at(kSeqI));
  emit("place r5, 8");
  emit("mul r5, r4, r5");
  emit("place r1, 64");
  emit("add r5, r5, r1");
  emit("load.64 r0, " + at(kSeqB));
  emit("add r5, r0, r5");
  emit("ldi.octet r5, r5");
  emit("eq r0, r6, r5");
  emit("jz r0, obrseq_no");
  emit("load.64 r4, " + at(kSeqI));
  emit("place r1, 1");
  emit("add r4, r4, r1");
  jump("obrseq_loop");
  emit("obrseq_yes:");
  emit("place r0, 1");
  emit("load.64 r7, " + at(kSeqLink));
  emit("ret");
  emit("obrseq_no:");
  emit("place r0, 0");
  emit("load.64 r7, " + at(kSeqLink));
  emit("ret");

  emit("obrfind:");
  emit("store.64 r7, " + at(kFindLink));
  emit("store.64 r0, " + at(kFindObj));
  emit("store.64 r1, " + at(kFindKey));
  emit("store.64 r2, " + at(kFindStride));
  emit("store.64 r3, " + at(kFindMode));
  emit("place r4, 0");
  emit("eq r4, r0, r4");
  emit("jnz r4, obrhalt");
  emit("place r5, 64");
  emit("add r5, r0, r5");
  emit("ldi.64 r4, r5");
  emit("place r5, 1");
  emit("sub r4, r4, r5");
  emit("store.64 r4, " + at(kFindMask));
  emit("load.64 r0, " + at(kFindObj));
  emit("place r5, 128");
  emit("add r5, r0, r5");
  emit("ldi.64 r4, r5");
  emit("store.64 r4, " + at(kFindSlots));
  emit("load.64 r3, " + at(kFindMode));
  emit("place r4, 1");
  emit("eq r4, r3, r4");
  emit("jnz r4, obrfind_str");
  emit("load.64 r0, " + at(kFindKey));
  emit("call obrmix");
  jump("obrfind_masked");
  emit("obrfind_str:");
  emit("load.64 r0, " + at(kFindKey));
  emit("call obrhash");
  emit("obrfind_masked:");
  emit("load.64 r1, " + at(kFindMask));
  emit("and r0, r0, r1");
  emit("store.64 r0, " + at(kFindStart));
  emit("store.64 r0, " + at(kFindIndex));
  emit("place r0, 0");
  emit("store.64 r0, " + at(kFindTomb));
  emit("obrfind_loop:");
  emit("load.64 r0, " + at(kFindSlots));
  emit("load.64 r1, " + at(kFindIndex));
  emit("load.64 r2, " + at(kFindStride));
  emit("mul r1, r1, r2");
  emit("add r0, r0, r1");
  emit("store.64 r0, " + at(kFindAddr));
  emit("ldi.64 r1, r0");
  emit("place r2, 0");
  emit("eq r3, r1, r2");
  emit("jnz r3, obrfind_empty");
  emit("place r2, 1");
  emit("eq r3, r1, r2");
  emit("jnz r3, obrfind_live");
  emit("load.64 r2, " + at(kFindTomb));
  emit("place r3, 0");
  emit("eq r3, r2, r3");
  emit("jz r3, obrfind_next");
  emit("load.64 r0, " + at(kFindAddr));
  emit("store.64 r0, " + at(kFindTomb));
  jump("obrfind_next");
  emit("obrfind_empty:");
  emit("load.64 r0, " + at(kFindTomb));
  emit("place r1, 0");
  emit("eq r2, r0, r1");
  emit("jz r2, obrfind_insert");
  emit("load.64 r0, " + at(kFindAddr));
  emit("obrfind_insert:");
  emit("place r1, 0");
  jump("obrfind_ret");
  emit("obrfind_live:");
  emit("load.64 r0, " + at(kFindAddr));
  emit("place r5, 64");
  emit("add r5, r0, r5");
  emit("ldi.64 r0, r5");
  emit("load.64 r1, " + at(kFindKey));
  emit("load.64 r3, " + at(kFindMode));
  emit("place r4, 1");
  emit("eq r4, r3, r4");
  emit("jnz r4, obrfind_seq");
  emit("place r4, 2");
  emit("eq r4, r3, r4");
  emit("jnz r4, obrfind_feq");
  emit("eq r4, r0, r1");
  emit("jnz r4, obrfind_hit");
  jump("obrfind_next");
  emit("obrfind_seq:");
  emit("call obrseq");
  emit("place r1, 1");
  emit("eq r4, r0, r1");
  emit("jnz r4, obrfind_hit");
  jump("obrfind_next");
  emit("obrfind_feq:");
  emit("feq r4, r0, r1");
  emit("jnz r4, obrfind_hit");
  jump("obrfind_next");
  emit("obrfind_hit:");
  emit("load.64 r0, " + at(kFindAddr));
  emit("place r1, 1");
  jump("obrfind_ret");
  emit("obrfind_next:");
  emit("load.64 r0, " + at(kFindIndex));
  emit("place r1, 1");
  emit("add r0, r0, r1");
  emit("load.64 r1, " + at(kFindMask));
  emit("and r0, r0, r1");
  emit("store.64 r0, " + at(kFindIndex));
  emit("load.64 r1, " + at(kFindStart));
  emit("eq r2, r0, r1");
  emit("jnz r2, obrfind_wrap");
  jump("obrfind_loop");
  emit("obrfind_wrap:");
  emit("load.64 r0, " + at(kFindTomb));
  emit("place r1, 0");
  emit("eq r2, r0, r1");
  emit("jnz r2, obrfind_full");
  emit("place r1, 0");
  jump("obrfind_ret");
  emit("obrfind_full:");
  emit("place r0, 0");
  emit("place r1, 0");
  emit("obrfind_ret:");
  emit("store.64 r0, " + at(kFindAddr));
  emit("store.64 r1, " + at(kFlag));
  emit("load.64 r7, " + at(kFindLink));
  emit("load.64 r0, " + at(kFindAddr));
  emit("load.64 r1, " + at(kFlag));
  emit("ret");

  emit("obrgrow:");
  emit("store.64 r7, " + at(kGrowLink));
  emit("store.64 r0, " + at(kGrowObj));
  emit("store.64 r2, " + at(kGrowStride));
  emit("store.64 r3, " + at(kGrowMode));
  emit("place r5, 64");
  emit("add r5, r0, r5");
  emit("ldi.64 r4, r5");
  emit("store.64 r4, " + at(kGrowCap));
  emit("place r5, 2");
  emit("mul r0, r4, r5");
  emit("store.64 r0, " + at(kGrowNew));
  emit("load.64 r2, " + at(kGrowStride));
  emit("mul r0, r0, r2");
  emit("call obrcheap");
  emit("store.64 r0, " + at(kGrowSlots));
  emit("load.64 r0, " + at(kGrowObj));
  emit("place r5, 128");
  emit("add r5, r0, r5");
  emit("ldi.64 r4, r5");
  emit("store.64 r4, " + at(kGrowOld));
  emit("place r4, 0");
  emit("store.64 r4, " + at(kGrowI));
  emit("obrgrow_loop:");
  emit("load.64 r0, " + at(kGrowI));
  emit("load.64 r1, " + at(kGrowCap));
  emit("lt r2, r0, r1");
  emit("jz r2, obrgrow_done");
  emit("load.64 r1, " + at(kGrowOld));
  emit("load.64 r2, " + at(kGrowStride));
  emit("mul r0, r0, r2");
  emit("add r0, r1, r0");
  emit("ldi.64 r1, r0");
  emit("place r2, 1");
  emit("eq r3, r1, r2");
  emit("jz r3, obrgrow_step");
  emit("place r5, 64");
  emit("add r5, r0, r5");
  emit("ldi.64 r1, r5");
  emit("store.64 r1, " + at(kGrowKey));
  emit("load.64 r2, " + at(kGrowStride));
  emit("place r3, 192");
  emit("eq r4, r2, r3");
  emit("jz r4, obrgrow_noval");
  emit("place r5, 128");
  emit("add r5, r0, r5");
  emit("ldi.64 r1, r5");
  emit("store.64 r1, " + at(kGrowVal));
  emit("obrgrow_noval:");
  emit("load.64 r3, " + at(kGrowMode));
  emit("place r4, 1");
  emit("eq r4, r3, r4");
  emit("jnz r4, obrgrow_hashs");
  emit("load.64 r0, " + at(kGrowKey));
  emit("call obrmix");
  jump("obrgrow_place");
  emit("obrgrow_hashs:");
  emit("load.64 r0, " + at(kGrowKey));
  emit("call obrhash");
  emit("obrgrow_place:");
  emit("load.64 r1, " + at(kGrowNew));
  emit("place r2, 1");
  emit("sub r1, r1, r2");
  emit("and r0, r0, r1");
  emit("store.64 r0, " + at(kFindIndex));
  emit("obrgrow_probe:");
  emit("load.64 r1, " + at(kGrowSlots));
  emit("load.64 r2, " + at(kFindIndex));
  emit("load.64 r3, " + at(kGrowStride));
  emit("mul r2, r2, r3");
  emit("add r1, r1, r2");
  emit("ldi.64 r2, r1");
  emit("place r3, 0");
  emit("eq r3, r2, r3");
  emit("jnz r3, obrgrow_put");
  emit("load.64 r0, " + at(kFindIndex));
  emit("place r2, 1");
  emit("add r0, r0, r2");
  emit("load.64 r2, " + at(kGrowNew));
  emit("place r3, 1");
  emit("sub r2, r2, r3");
  emit("and r0, r0, r2");
  emit("store.64 r0, " + at(kFindIndex));
  jump("obrgrow_probe");
  emit("obrgrow_put:");
  emit("place r2, 1");
  emit("sti.64 r2, r1");
  emit("store.64 r1, " + at(kFindAddr));
  emit("place r5, 64");
  emit("add r5, r1, r5");
  emit("load.64 r2, " + at(kGrowKey));
  emit("sti.64 r2, r5");
  emit("load.64 r2, " + at(kGrowStride));
  emit("place r3, 192");
  emit("eq r4, r2, r3");
  emit("jz r4, obrgrow_step");
  emit("load.64 r1, " + at(kFindAddr));
  emit("place r5, 128");
  emit("add r5, r1, r5");
  emit("load.64 r2, " + at(kGrowVal));
  emit("sti.64 r2, r5");
  emit("obrgrow_step:");
  emit("load.64 r0, " + at(kGrowI));
  emit("place r1, 1");
  emit("add r0, r0, r1");
  emit("store.64 r0, " + at(kGrowI));
  jump("obrgrow_loop");
  emit("obrgrow_done:");
  emit("load.64 r0, " + at(kGrowObj));
  emit("place r5, 64");
  emit("add r5, r0, r5");
  emit("load.64 r1, " + at(kGrowNew));
  emit("sti.64 r1, r5");
  emit("load.64 r0, " + at(kGrowObj));
  emit("place r5, 128");
  emit("add r5, r0, r5");
  emit("load.64 r1, " + at(kGrowSlots));
  emit("sti.64 r1, r5");
  emit("load.64 r7, " + at(kGrowLink));
  emit("ret");

  auto header = [&](const std::string& name, int headerBits, int stride, int cap) {
    emit(name + ":");
    emit("store.64 r7, " + at(kLink));
    emit("place r0, " + std::to_string(headerBits));
    emit("call obrcheap");
    emit("store.64 r0, " + at(kObj));
    emit("place r0, " + std::to_string(cap * stride));
    emit("call obrcheap");
    emit("store.64 r0, " + at(kVal));
    emit("load.64 r0, " + at(kObj));
    emit("place r1, 0");
    emit("sti.64 r1, r0");
    emit("place r5, 64");
    emit("add r5, r0, r5");
    emit("place r1, " + std::to_string(cap));
    emit("sti.64 r1, r5");
    emit("load.64 r0, " + at(kObj));
    emit("place r5, 128");
    emit("add r5, r0, r5");
    emit("load.64 r1, " + at(kVal));
    emit("sti.64 r1, r5");
    emit("load.64 r0, " + at(kObj));
    emit("load.64 r7, " + at(kLink));
    emit("ret");
  };
  header("obrsnew", 192, 128, 8);
  header("obrmnew", 192, 192, 8);

  emit("obranew:");
  emit("store.64 r7, " + at(kLink));
  emit("place r1, 0");
  emit("lt r1, r0, r1");
  emit("jnz r1, obrhalt");
  emit("store.64 r0, " + at(kKey));
  emit("place r1, 64");
  emit("mul r0, r0, r1");
  emit("place r1, 64");
  emit("add r0, r0, r1");
  emit("call obrcheap");
  emit("store.64 r0, " + at(kObj));
  emit("load.64 r1, " + at(kKey));
  emit("sti.64 r1, r0");
  emit("load.64 r0, " + at(kObj));
  emit("load.64 r7, " + at(kLink));
  emit("ret");

  emit("obrlnew:");
  emit("store.64 r7, " + at(kLink));
  emit("place r0, 192");
  emit("call obrcheap");
  emit("store.64 r0, " + at(kObj));
  emit("place r0, 256");
  emit("call obrcheap");
  emit("store.64 r0, " + at(kVal));
  emit("load.64 r0, " + at(kObj));
  emit("place r1, 0");
  emit("sti.64 r1, r0");
  emit("place r5, 64");
  emit("add r5, r0, r5");
  emit("place r1, 4");
  emit("sti.64 r1, r5");
  emit("load.64 r0, " + at(kObj));
  emit("place r5, 128");
  emit("add r5, r0, r5");
  emit("load.64 r1, " + at(kVal));
  emit("sti.64 r1, r5");
  emit("load.64 r0, " + at(kObj));
  emit("load.64 r7, " + at(kLink));
  emit("ret");

  auto bounds = [&](const std::string& name, bool buffered) {
    emit(name + ":");
    emit("store.64 r7, " + at(kLink));
    emit("place r2, 0");
    emit("eq r2, r0, r2");
    emit("jnz r2, obrhalt");
    emit("store.64 r0, " + at(kObj));
    emit("store.64 r1, " + at(kKey));
    emit("ldi.64 r2, r0");
    emit("place r3, 0");
    emit("lt r3, r1, r3");
    emit("jnz r3, obrhalt");
    emit("lt r3, r1, r2");
    emit("jz r3, obrhalt");
    emit("place r2, 64");
    emit("mul r1, r1, r2");
    if (buffered) {
      emit("load.64 r0, " + at(kObj));
      emit("place r5, 128");
      emit("add r5, r0, r5");
      emit("ldi.64 r0, r5");
      emit("add r0, r0, r1");
    } else {
      emit("place r2, 64");
      emit("add r1, r1, r2");
      emit("load.64 r0, " + at(kObj));
      emit("add r0, r0, r1");
    }
    emit("load.64 r7, " + at(kLink));
    emit("ret");
  };
  bounds("obrcidx", false);
  bounds("obrlidx", true);

  emit("obrlpush:");
  emit("store.64 r7, " + at(kLink));
  emit("place r2, 0");
  emit("eq r2, r0, r2");
  emit("jnz r2, obrhalt");
  emit("store.64 r0, " + at(kObj));
  emit("store.64 r1, " + at(kVal));
  emit("ldi.64 r2, r0");
  emit("store.64 r2, " + at(kKey));
  emit("place r5, 64");
  emit("add r5, r0, r5");
  emit("ldi.64 r3, r5");
  emit("lt r4, r2, r3");
  emit("jnz r4, obrlpush_store");
  emit("place r4, 2");
  emit("mul r0, r3, r4");
  emit("store.64 r0, " + at(kMode));
  emit("place r1, 64");
  emit("mul r0, r0, r1");
  emit("call obrcheap");
  emit("store.64 r0, " + at(kSlot));
  emit("load.64 r0, " + at(kObj));
  emit("place r5, 128");
  emit("add r5, r0, r5");
  emit("ldi.64 r1, r5");
  emit("load.64 r0, " + at(kSlot));
  emit("load.64 r2, " + at(kKey));
  emit("place r3, 0");
  emit("obrlpush_copy:");
  emit("lt r4, r3, r2");
  emit("jz r4, obrlpush_copied");
  emit("place r4, 64");
  emit("mul r4, r3, r4");
  emit("add r5, r1, r4");
  emit("ldi.64 r6, r5");
  emit("add r5, r0, r4");
  emit("sti.64 r6, r5");
  emit("place r4, 1");
  emit("add r3, r3, r4");
  emit("load.64 r2, " + at(kKey));
  jump("obrlpush_copy");
  emit("obrlpush_copied:");
  emit("load.64 r0, " + at(kObj));
  emit("place r5, 128");
  emit("add r5, r0, r5");
  emit("load.64 r1, " + at(kSlot));
  emit("sti.64 r1, r5");
  emit("load.64 r0, " + at(kObj));
  emit("place r5, 64");
  emit("add r5, r0, r5");
  emit("load.64 r1, " + at(kMode));
  emit("sti.64 r1, r5");
  emit("obrlpush_store:");
  emit("load.64 r0, " + at(kObj));
  emit("place r5, 128");
  emit("add r5, r0, r5");
  emit("ldi.64 r1, r5");
  emit("load.64 r2, " + at(kKey));
  emit("place r3, 64");
  emit("mul r2, r2, r3");
  emit("add r1, r1, r2");
  emit("load.64 r2, " + at(kVal));
  emit("sti.64 r2, r1");
  emit("load.64 r0, " + at(kObj));
  emit("load.64 r1, " + at(kKey));
  emit("place r2, 1");
  emit("add r1, r1, r2");
  emit("sti.64 r1, r0");
  emit("load.64 r7, " + at(kLink));
  emit("ret");

  emit("obrlpop:");
  emit("store.64 r7, " + at(kLink));
  emit("place r1, 0");
  emit("eq r1, r0, r1");
  emit("jnz r1, obrhalt");
  emit("store.64 r0, " + at(kObj));
  emit("ldi.64 r1, r0");
  emit("place r2, 0");
  emit("eq r2, r1, r2");
  emit("jnz r2, obrhalt");
  emit("place r2, 1");
  emit("sub r1, r1, r2");
  emit("sti.64 r1, r0");
  emit("store.64 r1, " + at(kKey));
  emit("place r5, 128");
  emit("add r5, r0, r5");
  emit("ldi.64 r0, r5");
  emit("place r2, 64");
  emit("mul r1, r1, r2");
  emit("add r5, r0, r1");
  emit("ldi.64 r0, r5");
  emit("load.64 r7, " + at(kLink));
  emit("ret");

  auto finishMut = [&](const std::string& growLabel, int stride, bool writeValue) {
    emit("store.64 r0, " + at(kSlot));
    emit("store.64 r1, " + at(kFlag));
    emit("load.64 r1, " + at(kFlag));
    emit("place r2, 1");
    emit("eq r2, r1, r2");
    emit(writeValue ? "jnz r2, " + growLabel + "_have" : "jnz r2, " + growLabel + "_done");
    emit("load.64 r0, " + at(kSlot));
    emit("place r1, 0");
    emit("eq r1, r0, r1");
    emit("jnz r1, " + growLabel + "_grow");
    emit("ldi.64 r1, r0");
    emit("place r2, 0");
    emit("eq r2, r1, r2");
    emit("jz r2, " + growLabel + "_write");
    emit("load.64 r3, " + at(kObj));
    emit("ldi.64 r4, r3");
    emit("place r5, 1");
    emit("add r4, r4, r5");
    emit("sti.64 r4, r3");
    emit(growLabel + "_write:");
    emit("load.64 r0, " + at(kSlot));
    emit("place r1, 1");
    emit("sti.64 r1, r0");
    emit("place r5, 64");
    emit("add r5, r0, r5");
    emit("load.64 r1, " + at(kKey));
    emit("sti.64 r1, r5");
    if (writeValue) {
      emit("load.64 r0, " + at(kSlot));
      emit("place r5, 128");
      emit("add r5, r0, r5");
      emit("load.64 r1, " + at(kVal));
      emit("sti.64 r1, r5");
    }
    jump(growLabel + "_done");
    emit(growLabel + "_have:");
    if (writeValue) {
      emit("load.64 r0, " + at(kSlot));
      emit("place r5, 128");
      emit("add r5, r0, r5");
      emit("load.64 r1, " + at(kVal));
      emit("sti.64 r1, r5");
    }
    emit(growLabel + "_done:");
    emit("load.64 r7, " + at(kLink));
    emit("ret");
    emit(growLabel + "_grow:");
    emit("load.64 r0, " + at(kObj));
    emit("place r2, " + std::to_string(stride));
    emit("load.64 r3, " + at(kMode));
    emit("call obrgrow");
    jump(growLabel + "_retry");
  };

  emit("obrsadd:");
  emit("store.64 r7, " + at(kLink));
  emit("store.64 r0, " + at(kObj));
  emit("store.64 r1, " + at(kKey));
  emit("store.64 r3, " + at(kMode));
  emit("obrsadd_retry:");
  emit("load.64 r0, " + at(kObj));
  emit("load.64 r1, " + at(kKey));
  emit("place r2, 128");
  emit("load.64 r3, " + at(kMode));
  emit("call obrfind");
  finishMut("obrsadd", 128, false);

  emit("obrmput:");
  emit("store.64 r7, " + at(kLink));
  emit("store.64 r0, " + at(kObj));
  emit("store.64 r1, " + at(kKey));
  emit("store.64 r2, " + at(kVal));
  emit("store.64 r3, " + at(kMode));
  emit("obrmput_retry:");
  emit("load.64 r0, " + at(kObj));
  emit("load.64 r1, " + at(kKey));
  emit("place r2, 192");
  emit("load.64 r3, " + at(kMode));
  emit("call obrfind");
  finishMut("obrmput", 192, true);

  emit("obrhas:");
  emit("store.64 r7, " + at(kLink));
  emit("call obrfind");
  emit("or r0, r1, r1");
  emit("load.64 r7, " + at(kLink));
  emit("ret");

  emit("obrget:");
  emit("store.64 r7, " + at(kLink));
  emit("store.64 r3, " + at(kMode));
  emit("place r2, 192");
  emit("load.64 r3, " + at(kMode));
  emit("call obrfind");
  emit("place r2, 1");
  emit("eq r2, r1, r2");
  emit("jz r2, obrhalt");
  emit("place r5, 128");
  emit("add r5, r0, r5");
  emit("ldi.64 r0, r5");
  emit("load.64 r7, " + at(kLink));
  emit("ret");

  emit("obrremove:");
  emit("store.64 r7, " + at(kLink));
  emit("store.64 r0, " + at(kObj));
  emit("store.64 r3, " + at(kMode));
  emit("load.64 r3, " + at(kMode));
  emit("call obrfind");
  emit("place r2, 1");
  emit("eq r2, r1, r2");
  emit("jz r2, obrremove_done");
  emit("place r1, 2");
  emit("sti.64 r1, r0");
  emit("load.64 r3, " + at(kObj));
  emit("ldi.64 r4, r3");
  emit("place r5, 1");
  emit("sub r4, r4, r5");
  emit("sti.64 r4, r3");
  emit("obrremove_done:");
  emit("load.64 r7, " + at(kLink));
  emit("ret");
}

}
